CREATE OR REPLACE PROCEDURE HR.LOG_AUDIT(
  p_kind IN VARCHAR2,
  p_ref_id IN NUMBER
) IS
BEGIN
  INSERT INTO AUDIT_LOG (kind, ref_id, logged_at)
  VALUES (p_kind, p_ref_id, SYSDATE);
END LOG_AUDIT;
/
GRANT EXECUTE ON HR.LOG_AUDIT TO APP_USER;
