CREATE OR REPLACE PROCEDURE FIN.PRC_UPDATE_MEMO(
  p_invoice_id IN NUMBER,
  p_memo       IN VARCHAR2
) IS
BEGIN
  UPDATE INVOICE
     SET memo = p_memo, updated_at = SYSDATE
   WHERE invoice_id = p_invoice_id;
  COMMIT;
END PRC_UPDATE_MEMO;
/

CREATE OR REPLACE PROCEDURE FIN.PRC_PING IS
BEGIN
  DBMS_OUTPUT.PUT_LINE('ok');
END PRC_PING;
/
